name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      image_name_lower: ${{ steps.set-names.outputs.lower }}

    steps:
      - name: Checkout code (Repo App)
        uses: actions/checkout@v4

      # Bước này sẽ tự động lấy tên repo của bạn (dinhvanan307/midterm-gitops)
      - name: Set lower-case image name
        id: set-names
        run: |
          LOWER_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LOWER=$LOWER_NAME" >> $GITHUB_ENV
          echo "lower=$LOWER_NAME" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Dùng tên repo của bạn đã được đổi thành chữ thường
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}
          tags: |
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update-manifest:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code (Repo Manifest)
        uses: actions/checkout@v4
        with:
          # --- ĐÂY LÀ DÒNG BẠN CẦN THAY THẾ ---
          # Thay bằng tên repo chứa file manifest (deployment.yaml) của bạn
          repository: dinhvanan307/midterm-gitops
          token: ${{ secrets.GIT_PAT }} 

      - name: Get new image tag and name
        run: |
          echo "NEW_TAG=${{ needs.build-and-push.outputs.image_tag }}" >> $GITHUB_ENV
          echo "IMAGE_NAME_LOWER=${{ needs.build-and-push.outputs.image_name_lower }}" >> $GITHUB_ENV

      - name: Update image tag in deployment.yaml
        run: |
          # Dùng 'sed' để cập nhật image, nó sẽ tự động dùng tên image đúng
          sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.NEW_TAG }}|g" deployment.yaml
          cat deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${{ env.NEW_TAG }}" || echo "No changes to commit"
          git push